# Generated by Django 3.2.7 on 2021-11-28 09:15

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=100)),
                ('last', models.CharField(max_length=100)),
                ('date', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('Z', 'Prefer Not to Say'), ('M', 'Male'), ('F', 'Female'), ('X', 'X')], default='Z', max_length=1)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
    ]
