# Generated by Django 3.2.7 on 2021-11-29 14:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[(' ', 'Prefer Not to Say'), ('M', 'Male'), ('F', 'Female'), ('X', 'X')], default=' ', max_length=1),
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vitals_date', models.DateField(verbose_name='Date')),
                ('respiration', models.IntegerField()),
                ('pulse', models.IntegerField()),
                ('systolic', models.IntegerField()),
                ('diastolic', models.IntegerField()),
                ('consciousness', models.CharField(choices=[('alert', 'Alert'), ('voice', 'Voice'), ('pain', 'Pain'), ('unresponsive', 'Unresponsive')], max_length=20, verbose_name='Level Of Consciousness')),
                ('gcs', models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)], verbose_name='Glasgow Coma Scale')),
                ('pupils', models.CharField(choices=[('normal', 'Normal'), ('dilated', 'Dilated'), ('Constricted', 'Constricted'), ('sluggish', 'sluggish'), ('no reaction', 'No Reaction')], max_length=20, verbose_name='pupils')),
                ('skin', models.CharField(choices=[('unremarkable', 'Unremarkable'), ('cool', 'cool'), ('moist', 'Moist'), ('warm', 'Warm'), ('dry', 'dry'), ('pale', 'Pale'), ('cyanotic', 'Cyanotic'), ('flushed', 'Flushed'), ('juandiced', 'Juandiced')], default='unremarkable', max_length=20, verbose_name='Skin')),
                ('status', models.CharField(choices=[('C', 'Critical'), ('U', 'Unstable'), ('P', 'Potentially Unstable'), ('S', 'Stable')], max_length=20, verbose_name='Status')),
                ('notes', models.TextField(max_length=250)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.patient')),
            ],
        ),
    ]
