# Generated by Django 3.2.7 on 2021-12-01 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_vitals_gcs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vitals',
            name='notes',
        ),
    ]
